### ISSUE TITLE
论文封面与教务处发布的本科生毕业论文内封面不一致

### ISSUE THREAD

**Issue by linncy** [YijunYuan/ECNU-Undergraduate-LaTeX#2]
封面与华东师范大学教务处下发的《关于做好2014级本科生毕业论文（设计）工作的通知》中的封面不一致，希望能够按照教务处文件进行修改，谢谢！

**Comment by YijunYuan** [comment]
你好！我这里的封面是内封面。根据《华东师范大学本科生毕业论文（设计）的格式要求》，内封面唯一的要求是
>四、封面要求
>上交的每份论文都一律采用学校统一印发的外封面（装订线一律在左面）。另附自制内封面一份（A4纸张电脑打印），内容为中外文论文题目、作者的姓名、学号、班级、指导老师的姓名与职称、论文完成时间。

而这些内容在这份模板的（内）封面中都已经提供了。
至于外封面会由学校统一印发，因此我这里没有制作。
另外，我并没有在《关于做好2014级本科生毕业论文(设计)工作的通知》的文档中找到关于封面格式的其他要求。不知道你说的是什么呢？

**Comment by linncy** [comment]
我看到《关于做好2014级本科生毕业论文(设计)工作的通知》的文档中有“本科生毕业论文内封面.docx”这个文件，认为内封面需要参照这个文档。如果内封面可以自定义的话，可以关闭这个issue了。
感谢回复。

**Comment by YijunYuan** [comment]
封面已改
