### ISSUE TITLE
word版模板中有页眉

### ISSUE THREAD

**Issue by hb4ch** [YijunYuan/ECNU-Undergraduate-LaTeX#4]
希望能够增加一下

**Comment by TsukuyomiJolno** [comment]
In package_and_setting.tex, Update these lines
\lhead{} -> \lhead{华东师范大学学士学位论文}
\rhead{} -> \rhead{\TitleCHS}

**Comment by YijunYuan** [comment]
楼上的老铁们我最近在忙着写初稿。。。等我忙完了就改搞。。。

**Comment by hb4ch** [comment]
还有老铁们，系统以及TeX Live里面的SimSun字体只有regular怎么办。如果直接编译的话所有的加粗都会失效。

**Comment by YijunYuan** [comment]
页眉我加好了，有需求的同学可以看一下。
