### ISSUE TITLE
一些问题20190413

### ISSUE THREAD

**Issue by JohnieChen** [YijunYuan/ECNU-Undergraduate-LaTeX#7]
1. 目录
目录我个人觉得其实是些小问题。一个是摘要和页码中间没有点连接，一个是页码之间的行距有点大。

2. 摘要
这个版本里摘要有三个地方需要改
2.1 中英文摘要都是有页眉页脚的，因此需要把`\thispagestyle{plain}`改成`\thispagestyle{fancy}`
2.2 摘要页不需要论文题目，因此可以直接删去。
2.3 摘要首行需要空一行，可以在摘要正文部分前一行插入`\vspace{1em}`

3. 正文
正文页脚居中，在package_and_settings.tex中修改
`%设置页眉页脚`
`\usepackage{fancyhdr}`
`\lhead{华东师范大学学士学位论文}`
`\chead{}`
`\rhead{\TitleCHS}`
`\lfoot{}`
`\cfoot{}`
`\rfoot{\thepage}`
为
`%设置页眉页脚`
`\usepackage{fancyhdr}`
`\lhead{华东师范大学学士学位论文}`
`\chead{}`
`\rhead{\TitleCHS}`
`\lfoot{}`
`\cfoot{\thepage}`
`\rfoot{}`

4. 编号格式
个人修改如下
`\setcounter{secnumdepth}{5}`
`\ctexset { section = { name={,.},number={\arabic{section}},format={ \sffamily \zihao {-4}} } }`
`\ctexset { subsection = { name={,},number={\arabic{section}.\arabic{subsection}},format={ \sffamily \zihao {-4}} } }`
`\ctexset { subsubsection = { name={,},number={\arabic{section}.\arabic{subsection}.\arabic{subsubsection}},format={\sffamily \zihao {-4}} } }`
`\ctexset { paragraph = { name={,},number={\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}},format={\sffamily \zihao {-4}} } }`
`\ctexset { subparagraph = { name={,）},number={\arabic{subparagraph}},format={\sffamily \zihao {-4}} } }`
但是这么改会造成参考文献、附录、致谢部分也跟着一起跑到左边了，这个问题有待解决

5. 图表
一个例子，图4-2代表第四章的第2张图可以在package_and_settings.tex中增加一行`\renewcommand {\thetable} {\arabic{section}-\arabic{table}}`

6. 脚注
脚注格式长这样①，因此这部分应修改为`\renewcommand{\thefootnote}{\textcircled{\arabic{footnote}}}

**Comment by JohnieChen** [comment]
补充一下，图表如果加上这行代码的话，每一个section的首行还要加一行`\setcounter{table}{0}`（至少我用的笨办法是这个

**Comment by JohnieChen** [comment]
补充2：附录要求也有一点问题，如果是直接
`\apdx{xxxx}`
`\apdx{yyyy}`
的话，输出结果就会变成“**附录一、xxxx**”和“**附录二、 yyyy**”。根据要求的话应该是只有“**附录**”一个大标题，其余的应该是以不会在目录中出现的那种副标题出现的，希望可以解决一下。

**Comment by YijunYuan** [comment]
已修
